# Generated by Django 4.1.7 on 2023-04-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
                ('Mileage', models.IntegerField()),
                ('Transmission', models.CharField(max_length=20)),
                ('Seats', models.IntegerField()),
                ('Fuel', models.CharField(max_length=20)),
                ('Airconditions', models.BooleanField(verbose_name=False)),
                ('ChildSeat', models.BooleanField(verbose_name=False)),
                ('GeoPS', models.BooleanField(verbose_name=False)),
                ('Luggage', models.BooleanField(verbose_name=False)),
                ('Music', models.BooleanField(verbose_name=False)),
                ('SeatBelt', models.BooleanField(verbose_name=False)),
                ('SleepingBed', models.BooleanField(verbose_name=False)),
                ('Water', models.BooleanField(verbose_name=False)),
                ('Bluetooth', models.BooleanField(verbose_name=False)),
                ('Onboardcomputer', models.BooleanField(verbose_name=False)),
                ('Audioinput', models.BooleanField(verbose_name=False)),
                ('LongTermTrips', models.BooleanField(verbose_name=False)),
                ('CarKit', models.BooleanField(verbose_name=False)),
                ('Remotecentrallocking', models.BooleanField(verbose_name=False)),
                ('Climatecontrol', models.BooleanField(verbose_name=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('pikeup_date', models.CharField(max_length=50)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.user')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.voiture')),
            ],
        ),
    ]
