# Generated by Django 4.1.7 on 2023-04-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
